import React from 'react';

function Terms() {
  return (
    <div className="min-h-screen bg-[#ecfeff] py-16 px-4 flex items-center justify-center">
      <div className="max-w-3xl w-full bg-white rounded-2xl shadow-lg p-8">
        <h1 className="text-4xl font-bold text-cyan-700 mb-8 text-center">Terms of Service</h1>
        <div className="text-cyan-900 space-y-6">
          <div>
            <div className="font-bold text-lg mb-2">Effective Date: October 4, 2024</div>
            <p>Thank you for choosing KOLCO COMMERCE PRIVATE LIMITED ("GoGetWell AI","Go Get Well", "we," "our," or "us"). These Terms of Service ("Terms") govern your use of our AI-powered medical tourism platform, including our software applications, websites, and any other services we offer (collectively, "Services"). By accessing or using our Services, you agree to be bound by these Terms.</p>
          </div>
          <div>
            <h2 className="text-xl font-bold text-cyan-700 mb-2">1. Registration and Access</h2>
            <ul className="list-disc ml-6">
              <li>Minimum Age: You must be at least 18 years old to use our Services. If you are under 18, your use of the Services must be supervised by a parent or legal guardian who consents to these Terms on your behalf.</li>
              <li>Account Registration: You must provide accurate and complete information to register for an account. For healthcare facilitators, this includes valid business information. You are responsible for all activities under your account and must maintain the confidentiality of your credentials.</li>
            </ul>
          </div>
          <div>
            <h2 className="text-xl font-bold text-cyan-700 mb-2">2. Use of Our Services</h2>
            <ul className="list-disc ml-6">
              <li>Permitted Use: Subject to compliance with these Terms, you may access and use our Services for medical tourism purposes. You must comply with all applicable laws, including the Information Technology Act, 2000, and any other relevant regulations related to healthcare and tourism.</li>
              <li>Prohibited Activities:
                <ul className="list-disc ml-6">
                  <li>Infringe, misappropriate, or violate anyone's rights, including patient privacy rights.</li>
                  <li>Modify, copy, lease, sell, or distribute any part of our Services.</li>
                  <li>Attempt to reverse-engineer or discover the source code of our AI-powered Services.</li>
                  <li>Automatically extract data without our permission.</li>
                  <li>Use output generated by the Services for any purpose that could have a legal or material impact on a third party, especially in a medical context.</li>
                  <li>Interfere with the functionality of our medical tourism platform.</li>
                </ul>
              </li>
            </ul>
          </div>
          <div>
            <h2 className="text-xl font-bold text-cyan-700 mb-2">3. Intellectual Property Rights</h2>
            <p>We and our affiliates own all rights, title, and interest in the Services, including any content, software, and other intellectual property related to our AI-powered medical tourism solutions.</p>
          </div>
          <div>
            <h2 className="text-xl font-bold text-cyan-700 mb-2">4. Content</h2>
            <ul className="list-disc ml-6">
              <li>User Content: You may provide input to the Services ("Input"), including medical information, and receive output ("Output") such as treatment recommendations. You retain ownership of the Input you provide, and we assign to you all rights in the Output generated by the Services, subject to these Terms.</li>
              <li>Our Use of Content: We may use your Input and Output to develop, improve, and provide our medical tourism Services. If you do not want us to use your content for these purposes, please contact us.</li>
            </ul>
          </div>
          <div>
            <h2 className="text-xl font-bold text-cyan-700 mb-2">5. Disclaimer of Warranties</h2>
            <p>OUR SERVICES ARE PROVIDED "AS IS." WHILE WE STRIVE FOR ACCURACY IN OUR AI-POWERED RECOMMENDATIONS, WE DISCLAIM ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
          </div>
          <div>
            <h2 className="text-xl font-bold text-cyan-700 mb-2">6. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, we are not liable for any indirect, incidental, consequential, or punitive damages, or loss of profits, revenue, data, or business opportunities resulting from your use of our Services.</p>
          </div>
          <div>
            <h2 className="text-xl font-bold text-cyan-700 mb-2">7. Changes to These Terms</h2>
            <p>We may modify these Terms from time to time. If we make material changes, we will notify you by updating the effective date at the top of these Terms.</p>
          </div>
          <div>
            <h2 className="text-xl font-bold text-cyan-700 mb-2">8. Contact Us</h2>
            <p>If you have any questions about these Terms or our medical tourism services, please contact us at <a href="mailto:hello@gogetwell.ai" className="text-cyan-600 hover:underline">hello@gogetwell.ai</a>.</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Terms; 